### ISSUE TITLE
inotifywait crashes when editing haproxy.cfg with vim

### ISSUE THREAD

**Issue by mlofjard** [bringnow/docker-haproxy-letsencrypt#2]
Editing the haproxy config file with vim triggers a MOVE_SELF event that causes inotifywait to exit with code 1.

Suggestion:
Adding `-e create,modify,delete,move,move_self` to `inotifywait` loop solves the problem. Listening to the MOVE event as well makes it possible to manually move certificates into the certificate folder.

**Comment by christoph-jerolimov** [comment]
Thanks @mlofjard. This change works for you+vim? Can you create a PR?

**Comment by mlofjard** [comment]
This change made me able to edit the configuration with vim (the only available editor on CoreOS) and trigger the inotifywait-reload-loop. 
I will create a pull request tonight.

**Comment by fkoester** [comment]
Merged the PR, thanks 👍
